<a href="https://colab.research.google.com/github/Kamalakannan-1208/Python-Programming-Fundamentals/blob/main/Day_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sorting

In [1]:
import pandas as pd
df1={"Name":["kamal","shruthi","Kumar"],
     "Marks":[80,95,89],
     "Age":[21,20,19]}
df1=pd.DataFrame(df1)
df1

      Name  Marks  Age
0    kamal     80   21
1  shruthi     95   20
2    Kumar     89   19

In [2]:
df1.sort_values(by=["Marks","Age"],inplace=True,ascending=False)
df1

      Name  Marks  Age
1  shruthi     95   20
2    Kumar     89   19
0    kamal     80   21

In [3]:
df1.sort_values(by="Name",key=lambda x: x.str.lower())
df1

      Name  Marks  Age
1  shruthi     95   20
2    Kumar     89   19
0    kamal     80   21

Pivot table

In [4]:
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

In [5]:
pivot_df=pd.pivot_table(df,index=["Product","Category"],values=["Quantity","Amount"],aggfunc=["sum","mean","min",],margins=True)
pivot_df

                      sum                 mean             min
                   Amount Quantity      Amount Quantity Amount Quantity
Product  Category
Banana   Fruit       1091       15  363.666667    5.000     90        3
Beans    Vegetable    626        5  626.000000    5.000    626        5
Broccoli Vegetable    301       16  150.500000    8.000     62        5
Carrots  Vegetable    270        8  270.000000    8.000    270        8
Orange   Fruit        610        9  610.000000    9.000    610        9
All                  2898       53  362.250000    6.625     62        3

Series

In [6]:
series=pd.Series()
series

Series([], dtype: object)

In [8]:
# creation
series=pd.Series([1,2,3,4,5],index=['A','B',"C",'D',"E"])
series

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [10]:
series.reset_index(drop=True,inplace=True)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

Access sereis

In [11]:
series[0]

np.int64(1)

In [12]:
series[0:3]

0    1
1    2
2    3
dtype: int64

In [13]:
series.loc[3:]

3    4
4    5
dtype: int64

In [16]:
series.iloc[:]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
# binary operations
# arithmetic additon, sub, mul, div
series1=pd.Series([1,2,3,4,5])
series2=pd.Series([6,7,8,9,10])
series1+series2

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [18]:
# comparision
series1>series2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [22]:
#Logical operation
series1 | series2

0     7
1     7
2    11
3    13
4    15
dtype: int64

In [24]:
# aggregation
series1.sum()
# prod(),mean()

np.int64(15)

In [25]:
# pow
series1.pow(series2)

0          1
1        128
2       6561
3     262144
4    9765625
dtype: int64

In [26]:
# abs
series1.abs()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [28]:
series1.cov(series2)

np.float64(2.5)